 $(document).ready(function() {

 	$('#btnAutoGeneratedNumber').click(autoGeneratedNumber);
 	
 	$('.form_date').datetimepicker({
 		format : 'dd-mm-yyyy',
 		weekStart: 1,
 		todayBtn:  1,
 		autoclose: 1,
 		todayHighlight: 1,
 		startView: 2,
 		minView: 2,
 		forceParse: 0,
 		initialDate : new Date()
 	});

 	function autoGeneratedNumber(){

 		var type = $('#typeId option:selected').attr('class');
 		var organ = $('#organId').attr('class');
 		var unit = $('#unitId').attr('class');

 		var numberSign = '-'+ type + '/' + organ + '-' + unit;
  		$('#numberSign').val(numberSign);

 	}

 });