 $(document).ready(function() {

 	$('#btnAutoGeneratedNumber').click(autoGeneratedNumber);
 	
 	$('.form_date').datetimepicker({
 		format : 'dd-mm-yyyy',
 		weekStart: 1,
 		todayBtn:  1,
 		autoclose: 1,
 		todayHighlight: 1,
 		startView: 2,
 		minView: 2,
 		forceParse: 0,
 		initialDate : new Date()
 	});

 	$('.form_date').datetimepicker("setDate", new Date());
 	var timeWidth = $('#number').css('width');
 	$('#receiveTime').css('width', timeWidth);
 	
 	$(window).resize(function(){
 			timeWidth = $('#number').css('width');
 			$('#receiveTime').css('width', timeWidth);
 	});
 

 	function autoGeneratedNumber(){

 		var tenureId = $('.tenure').attr('data');
 		var organId = $('.rOrgan').attr('data');

 		$('#btnAutoGeneratedNumber').button('loading');

 		$.ajax({
 			type : "GET",
 			url : "number_in",
 			data : {
 				"tenureId" : tenureId,
 				"organId" : organId
 			},
 			success: function(response){
 				$('#number').val(response);
  				$('#btnAutoGeneratedNumber').button('reset');
            }
        });
 	}

 	$('#btnAssign').click(function(){
 		var strStart = $('#showTimeStart').html().split('-');
 		var strEnd = $('#showTimeEnd').html().split('-');
 		var content = $('#showContent').html();

 		$('.date-start').datetimepicker("setDate", new Date(strStart[2], strStart[1], strStart[0]));
 		$('.date-end').datetimepicker("setDate", new Date(strEnd[2], strEnd[1], strEnd[0]));
 		$('#content').html(content);
 	});

 	$('#btnTempReport').click(function(){
 		var report = $('#showReport').html();
 		$('#report').html(report);
 	});

 });
