 $(document).ready(function() {

 	$('#btnAutoGeneratedNumber').click(autoGeneratedNumber);
 	
 	$('.form_date').datetimepicker({
 		format : 'dd-mm-yyyy',
 		weekStart: 1,
 		todayBtn:  1,
 		autoclose: 1,
 		todayHighlight: 1,
 		startView: 2,
 		minView: 2,
 		forceParse: 0,
 		initialDate : new Date()
 	});

 	$('.form_date').datetimepicker("setDate", new Date());
 	var timeWidth = $('#number').css('width');
 	$('#receiveTime').css('width', timeWidth);
 	
 	$(window).resize(function(){
 			timeWidth = $('#number').css('width');
 			$('#receiveTime').css('width', timeWidth);
 	});
 

 	function autoGeneratedNumber(){

 		var tenureId = $('.tenure').attr('data');
 		var organId = $('.rOrgan').attr('data');

 		$('#btnAutoGeneratedNumber').button('loading');

 		$.ajax({
 			type : "GET",
 			url : "number_in",
 			data : {
 				"tenureId" : tenureId,
 				"organId" : organId
 			},
 			success: function(response){
 				$('#number').val(response);
  				$('#btnAutoGeneratedNumber').button('reset');
            }
        });
 	}

 });
